name = "BehaviorTree"
uuid = "f69da737-dcaa-4055-be2f-aa6e9fbb4bc4"
authors = ["Fabian D <fabian@datamaplab.com>"]
version = "0.3.2"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
julia = "1.4"
AbstractTrees = "0.3"
